project_name: sql-mcp-server
release:
  github:
    owner: your-org
    name: sql-mcp-server
  draft: false
  prerelease: "false"

builds:
  - id: sql-mcp-server
    main: ./cmd/main.go
    binary: sql-mcp-server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: darwin
        format: zip
    replacements:
      darwin: macOS
      amd64: x86_64
      arm64: arm64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

snapshots:
  - name_template: "snapshot"

BINARY_NAME=sql-mcp-server
CMD_DIR=./cmd

.PHONY: build clean test run lint release snapshot

build:
	go build -o $(BINARY_NAME) $(CMD_DIR)/main.go

clean:
	rm -f $(BINARY_NAME)

test:
	go test ./...

run:
	go run $(CMD_DIR)/main.go

lint:
	go vet ./...

release:
	goreleaser release --clean

snapshot:
	goreleaser release --snapshot --clean
