name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Build binaries
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/sql-mcp-server-linux-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/sql-mcp-server-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/sql-mcp-server-windows-amd64.exe

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
